MODULE nrtype

   INTEGER, PARAMETER :: I1B = SELECTED_INT_KIND(2)
   INTEGER, PARAMETER :: I2B = SELECTED_INT_KIND(4)
   INTEGER, PARAMETER :: I4B = SELECTED_INT_KIND(9)
   INTEGER, PARAMETER :: SP = KIND(1.0)
   INTEGER, PARAMETER :: DP = KIND(1.0D0)
   INTEGER, PARAMETER :: RP = SP

   TYPE :: PARTICLE 
      REAL(RP) :: x 
      REAL(RP) :: y 
      TYPE (PARTICLE), POINTER :: next 
   END TYPE

   TYPE :: PARTICLELINE 
      INTEGER :: length 
      TYPE (PARTICLE) :: Particles 
   END TYPE

   REAL(RP),ALLOCATABLE::DIV(:,:)
   REAL(RP) DX,DY

END MODULE nrtype
